package lifecycle

import (
 "context"
 "crypto/sha256"
 "encoding/hex"
 "errors"
 "fmt"
 "time"

 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/lock"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
)

type ActionRequest struct{OperationID string `json:"operation_id"`;IdempotencyKey string `json:"idempotency_key"`;Action string `json:"action"`;DestroyData bool `json:"destroy_data,omitempty"`}
func(e *Engine)Action(ctx context.Context,serviceID string,r ActionRequest)(model.Operation,error){if r.OperationID==""||r.IdempotencyKey==""{return model.Operation{},errors.New("operation_id and idempotency_key required")};switch r.Action{case "start","stop","restart","upgrade","repair","backup","restore","uninstall":default:return model.Operation{},errors.New("unsupported lifecycle action")};st,err:=e.Store.GetService(serviceID);if err!=nil{return model.Operation{},err};p,ok:=e.Registry.Get(st.Provider);if !ok{return model.Operation{},errors.New("provider unavailable")};sum:=sha256.Sum256([]byte(serviceID+"|"+r.Action+"|"+r.IdempotencyKey));op:=model.Operation{ID:r.OperationID,ServiceID:serviceID,IdempotencyKey:r.IdempotencyKey,RequestDigest:hex.EncodeToString(sum[:]),Status:model.OpRequested,Stage:r.Action};op,err=e.Store.Begin(op);if err!=nil{return op,err};if op.Status==model.OpSucceeded{return op,nil};if op.Status==model.OpUnknown{return op,errors.New("UNKNOWN operation requires authoritative observation before retry")};lk,err:=lock.Acquire(e.LockPath);if err!=nil{return op,err};defer lk.Release();op.Status=model.OpRunning;op.Stage=r.Action;op.Error="";_ = e.Store.SaveOperation(op);fail:=func(cause error,ambiguous bool)(model.Operation,error){op.Error=redact(cause.Error());if ambiguous{op.Status=model.OpUnknown}else{op.Status=model.OpFailedNeedsRecovery};_ = e.Store.SaveOperation(op);return op,cause};switch r.Action{case "start":err=p.Start(ctx,op,st);case "stop":err=p.Stop(ctx,op,st);case "restart":err=p.Restart(ctx,op,st);case "repair":plan:=model.Plan{ID:op.ID,ServiceID:st.ID,Provider:st.Provider,ResolvedVersion:st.ResolvedVersion,Digest:st.PlanDigest,CreatedAt:time.Now().UTC()};err=p.Repair(ctx,op,plan);case "backup":err=p.Backup(ctx,op,st);case "restore":err=p.Restore(ctx,op,st);case "upgrade":req:=model.ServiceRequest{SchemaVersion:1,RequestID:op.ID,ServiceID:st.ID,OperationID:op.ID,IdempotencyKey:r.IdempotencyKey,Category:st.Category,Provider:st.Provider,ReleaseLine:st.ReleaseLine,Topology:st.Topology};resolved,e2:=p.ResolveVersion(ctx,req);if e2!=nil{return fail(e2,false)};if resolved==st.ResolvedVersion{op.Status=model.OpSucceeded;op.Stage="already-current";_ = e.Store.SaveOperation(op);return op,nil};plan:=model.Plan{ID:op.ID,ServiceID:st.ID,Provider:st.Provider,ResolvedVersion:resolved,CreatedAt:time.Now().UTC()};err=p.Upgrade(ctx,op,plan);if err==nil{st.ResolvedVersion=resolved;st.UpdatedAt=time.Now().UTC();_ = e.Store.SaveService(st)};case "uninstall":return e.uninstallLocked(ctx,st,p,op,r.DestroyData)};if err!=nil{return fail(err,errors.Is(err,context.DeadlineExceeded)||errors.Is(err,context.Canceled))};if r.Action!="stop"&&r.Action!="backup"{h,herr:=p.Health(ctx,st);if herr!=nil{return fail(herr,false)};if !h.Healthy{return fail(fmt.Errorf("post-%s health failed: %s",r.Action,h.Error),false)}};op.Status=model.OpSucceeded;op.Stage="complete";op.Error="";_ = e.Store.SaveOperation(op);return op,nil}
func(e *Engine)uninstallLocked(ctx context.Context,st model.ServiceState,p interface{Uninstall(context.Context,model.Operation,model.ServiceState,bool)error;ResidueAudit(context.Context,model.ServiceState)(map[string]string,error)},op model.Operation,destroy bool)(model.Operation,error){if err:=p.Uninstall(ctx,op,st,destroy);err!=nil{op.Status=model.OpFailedNeedsRecovery;op.Error=redact(err.Error());_ = e.Store.SaveOperation(op);return op,err};res,err:=p.ResidueAudit(ctx,st);if err!=nil{return op,err};for _,v:=range res{if v=="present"||v=="active"{op.Status=model.OpFailedNeedsRecovery;op.Stage="residue-audit";op.Error="managed residue remains";_ = e.Store.SaveOperation(op);return op,errors.New("managed residue remains")}};st.Status="uninstalled-data-preserved";_ = e.Store.SaveService(st);op.Status=model.OpSucceeded;op.Stage="complete";op.Error="";_ = e.Store.SaveOperation(op);return op,nil}
