package lifecycle

import (
 "context"
 "errors"
 "fmt"
 "time"

 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/config"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/journal"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/lock"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/preflight"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/provider"
)

type Engine struct{Registry *provider.Registry;Store *journal.Store;LockPath string}
func(e *Engine)Plan(ctx context.Context,req model.ServiceRequest)(model.Plan,model.Operation,error){
 if err:=config.Validate(req);err!=nil{return model.Plan{},model.Operation{},err};p,ok:=e.Registry.Get(req.Provider);if !ok{return model.Plan{},model.Operation{},fmt.Errorf("unknown provider %q",req.Provider)};if p.Category()!=req.Category{return model.Plan{},model.Operation{},errors.New("provider category mismatch")};if err:=p.Validate(ctx,req);err!=nil{return model.Plan{},model.Operation{},err};if _,err:=preflight.System(ctx,req);err!=nil{return model.Plan{},model.Operation{},err};digest,err:=config.CanonicalDigest(req);if err!=nil{return model.Plan{},model.Operation{},err};op:=model.Operation{ID:req.OperationID,ServiceID:req.ServiceID,IdempotencyKey:req.IdempotencyKey,RequestDigest:digest,Status:model.OpPreflight,Stage:"preflight"};op,err=e.Store.Begin(op);if err!=nil{return model.Plan{},op,err};if op.Status==model.OpSucceeded||op.Status==model.OpRunning||op.Status==model.OpUnknown{return model.Plan{},op,fmt.Errorf("operation already in terminal/in-flight state %s",op.Status)};resolved,err:=p.ResolveVersion(ctx,req);if err!=nil{op.Status=model.OpFailedSafe;op.Stage="version-resolution";op.Error=redact(err.Error());_ = e.Store.SaveOperation(op);return model.Plan{},op,err};plan,err:=p.Plan(ctx,req,resolved);if err!=nil{op.Status=model.OpFailedSafe;op.Stage="planning";op.Error=redact(err.Error());_ = e.Store.SaveOperation(op);return model.Plan{},op,err};if err=e.Store.SavePlan(plan);err!=nil{return model.Plan{},op,err};op.PlanDigest=plan.Digest;op.Status=model.OpWaitingConfirmation;op.Stage="waiting-confirmation";op.Error="";if err=e.Store.SaveOperation(op);err!=nil{return model.Plan{},op,err};return plan,op,nil
}
func(e *Engine)Install(ctx context.Context,req model.ServiceRequest,confirmedPlanDigest string)(model.Operation,error){
 if err:=config.Validate(req);err!=nil{return model.Operation{},err};digest,err:=config.CanonicalDigest(req);if err!=nil{return model.Operation{},err};op,err:=e.Store.GetOperation(req.OperationID);if err!=nil{return op,err};if op.RequestDigest!=digest||op.IdempotencyKey!=req.IdempotencyKey{return op,errors.New("operation request/idempotency mismatch")};if op.Status==model.OpSucceeded{return op,nil};if op.Status==model.OpUnknown{return op,errors.New("UNKNOWN operation requires authoritative reconciliation before retry")};plan,err:=e.Store.GetPlan(req.OperationID);if err!=nil{return op,err};if confirmedPlanDigest==""||confirmedPlanDigest!=plan.Digest||confirmedPlanDigest!=op.PlanDigest{return op,errors.New("plan confirmation digest mismatch")};p,ok:=e.Registry.Get(req.Provider);if !ok{return op,errors.New("provider disappeared")};lk,err:=lock.Acquire(e.LockPath);if err!=nil{return op,err};defer lk.Release();op.Status=model.OpRunning;op.Stage="install";op.Error="";_ = e.Store.SaveOperation(op)
 fail:=func(stage string,cause error,ambiguous bool)(model.Operation,error){op.Stage=stage;op.Error=redact(cause.Error());if ambiguous{op.Status=model.OpUnknown}else{op.Status=model.OpFailedNeedsRecovery};_ = e.Store.SaveOperation(op);return op,cause}
 if err=p.Install(ctx,op,plan);err!=nil{return fail("install",err,errors.Is(err,context.DeadlineExceeded)||errors.Is(err,context.Canceled))};op.Stage="configure";_ = e.Store.SaveOperation(op);if err=p.Configure(ctx,op,plan);err!=nil{return fail("configure",err,false)};op.Stage="initialize";_ = e.Store.SaveOperation(op);if req.Topology=="cluster"{if err=p.Join(ctx,op,plan);err!=nil{return fail("join",err,false)}}else if err=p.Initialize(ctx,op,plan);err!=nil{return fail("initialize",err,false)};op.Status=model.OpVerifying;op.Stage="health";_ = e.Store.SaveOperation(op);st:=model.ServiceState{ID:req.ServiceID,Provider:req.Provider,Category:req.Category,ReleaseLine:req.ReleaseLine,ResolvedVersion:plan.ResolvedVersion,Topology:req.Topology,ConfigDigest:digest,PlanDigest:plan.Digest,Status:"installed",UpdatedAt:time.Now().UTC()};h,err:=p.Health(ctx,st);if err!=nil{return fail("health",err,false)};if !h.Healthy{return fail("health",errors.New(h.Error),false)};if err=e.Store.SaveService(st);err!=nil{return fail("commit-state",err,false)};op.Status=model.OpSucceeded;op.Stage="complete";op.Error="";_ = e.Store.SaveOperation(op);return op,nil
}
func(e *Engine)Health(ctx context.Context,id string)(model.HealthResult,error){st,err:=e.Store.GetService(id);if err!=nil{return model.HealthResult{},err};p,ok:=e.Registry.Get(st.Provider);if !ok{return model.HealthResult{},errors.New("provider unavailable")};return p.Health(ctx,st)}
func(e *Engine)Uninstall(ctx context.Context,id string,op model.Operation,destroyData bool)(model.Operation,error){st,err:=e.Store.GetService(id);if err!=nil{return op,err};p,ok:=e.Registry.Get(st.Provider);if !ok{return op,errors.New("provider unavailable")};lk,err:=lock.Acquire(e.LockPath);if err!=nil{return op,err};defer lk.Release();op.Status=model.OpRunning;op.Stage="uninstall";_ = e.Store.SaveOperation(op);if err=p.Uninstall(ctx,op,st,destroyData);err!=nil{op.Status=model.OpFailedNeedsRecovery;op.Error=redact(err.Error());_ = e.Store.SaveOperation(op);return op,err};res,err:=p.ResidueAudit(ctx,st);if err!=nil{return op,err};for _,v:=range res{if v=="present"||v=="active"{op.Status=model.OpFailedNeedsRecovery;op.Stage="residue-audit";op.Error="managed residue remains";_ = e.Store.SaveOperation(op);return op,errors.New("managed residue remains")}};st.Status="uninstalled-data-preserved";_ = e.Store.SaveService(st);op.Status=model.OpSucceeded;op.Stage="complete";op.Error="";_ = e.Store.SaveOperation(op);return op,nil}
func redact(s string)string{if len(s)>1024{s=s[:1024]};return s}
