package vip

import (
    "context"
    "crypto/sha256"
    "encoding/hex"
    "encoding/json"
    "errors"
    "fmt"
    "os"
    "path/filepath"
    "strings"
    "time"

    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/executor"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/filesystem"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/packageutil"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/vipexec"
)

const repoID="appstream"
type Manager struct{Runner executor.Runner;StateRoot string}
type state struct{ServiceID string `json:"service_id"`;Mode string `json:"mode"`;Address string `json:"address"`;PrefixLength int `json:"prefix_length"`;Interface string `json:"interface"`;CreatedAt time.Time `json:"created_at"`}

func(m Manager)AugmentPlan(ctx context.Context,req model.ServiceRequest,plan model.Plan)(model.Plan,error){v:=req.Network.VIP;if v.Mode==""{return plan,nil};switch v.Mode{case "secondary":plan.Steps=append(plan.Steps,model.PlanStep{Name:"vip-secondary",Action:fmt.Sprintf("persist secondary VIP %s/%d on NetworkManager interface %s before service start",v.Address,v.PrefixLength,v.Interface)});return plan,nil;case "vrrp":if m.Runner==nil{return plan,errors.New("VIP executor unavailable")};d:=packageutil.DNF{Runner:m.Runner};if err:=d.ValidateRepositories(ctx,repoID);err!=nil{return plan,err};repoDigest,err:=d.RepositoryDigest(ctx,repoID);if err!=nil{return plan,err};resolved,err:=d.ResolveLatestFromRepos(ctx,"keepalived",[]string{repoID});if err!=nil{return plan,err};plan.PlatformPackages=append(plan.PlatformPackages,model.PlatformPackagePin{Purpose:"vrrp",Package:"keepalived",ResolvedVersion:resolved,RepositoryID:repoID,RepositoryDigest:repoDigest});plan.Steps=append(plan.Steps,model.PlanStep{Name:"vrrp-package",Action:"install exact Keepalived package "+resolved+" from pinned Rocky AppStream repository"},model.PlanStep{Name:"vrrp-firewall",Action:"allow VRRP protocol only from the declared unicast peer addresses"},model.PlanStep{Name:"vrrp",Action:fmt.Sprintf("configure Keepalived %s state=%s interface=%s VIP=%s/%d VRID=%d priority=%d peers=%v",instanceName(req.ServiceID),v.State,v.Interface,v.Address,v.PrefixLength,v.VirtualRouterID,v.Priority,v.Peers)});return plan,nil;default:return plan,errors.New("unsupported VIP mode")}}

func(m Manager)Apply(ctx context.Context,serviceID string,n model.NetworkSpec,plan model.Plan)error{v:=n.VIP;if v.Mode==""{return nil};if m.Runner==nil{return errors.New("VIP executor unavailable")};if err:=m.ensureStateRoot();err!=nil{return err};recordPath:=filepath.Join(m.StateRoot,serviceID+".json");if old,ok,err:=readState(recordPath);err!=nil{return err}else if ok{if old.Mode!=v.Mode||old.Address!=v.Address||old.PrefixLength!=v.PrefixLength||old.Interface!=v.Interface{return errors.New("existing VIP ownership state conflicts with requested VIP")};return m.ensure(ctx,serviceID,n,plan)}
    switch v.Mode{case "secondary":_,err:=m.Runner.Run(ctx,vipexec.SecondaryAdd,v.Interface,fmt.Sprintf("%s/%d",v.Address,v.PrefixLength));if err!=nil{return err};case "vrrp":if err:=m.applyVRRP(ctx,serviceID,n,plan);err!=nil{return err};default:return errors.New("unsupported VIP mode")}
    b,_:=json.MarshalIndent(state{ServiceID:serviceID,Mode:v.Mode,Address:v.Address,PrefixLength:v.PrefixLength,Interface:v.Interface,CreatedAt:time.Now().UTC()},"","  ");return filesystem.AtomicWrite(recordPath,append(b,'\n'),0600,m.StateRoot)}
func(m Manager)Ensure(ctx context.Context,serviceID string,n model.NetworkSpec,plan model.Plan)error{if n.VIP.Mode==""{return nil};if err:=m.ensureStateRoot();err!=nil{return err};st,ok,err:=readState(filepath.Join(m.StateRoot,serviceID+".json"));if err!=nil{return err};if !ok||st.ServiceID!=serviceID||st.Mode!=n.VIP.Mode||st.Address!=n.VIP.Address{return errors.New("VIP recovery ownership cannot be proven")};return m.ensure(ctx,serviceID,n,plan)}
func(m Manager)ensure(ctx context.Context,serviceID string,n model.NetworkSpec,plan model.Plan)error{switch n.VIP.Mode{case "secondary":_,err:=m.Runner.Run(ctx,vipexec.SecondaryAdd,n.VIP.Interface,fmt.Sprintf("%s/%d",n.VIP.Address,n.VIP.PrefixLength));return err;case "vrrp":return m.applyVRRP(ctx,serviceID,n,plan)};return nil}
func(m Manager)Remove(ctx context.Context,serviceID string,n model.NetworkSpec)error{if n.VIP.Mode==""{return nil};if m.Runner==nil{return errors.New("VIP executor unavailable")};if err:=m.ensureStateRoot();err!=nil{return err};path:=filepath.Join(m.StateRoot,serviceID+".json");st,ok,err:=readState(path);if err!=nil{return err};if !ok{return nil};if st.ServiceID!=serviceID||st.Mode!=n.VIP.Mode||st.Address!=n.VIP.Address{return errors.New("VIP cleanup ownership mismatch")};switch n.VIP.Mode{case "secondary":if _,err=m.Runner.Run(ctx,vipexec.SecondaryRemove,n.VIP.Interface,fmt.Sprintf("%s/%d",n.VIP.Address,n.VIP.PrefixLength));err!=nil{return err};case "vrrp":_,_ = m.Runner.Run(ctx,"/usr/bin/systemctl","disable","--now","keepalived.service");_,_ = m.Runner.Run(ctx,vipexec.VRRPFirewallRemove,serviceID,n.VIP.Peers...);_,_ = m.Runner.Run(ctx,"/usr/bin/rm","-f","/etc/keepalived/keepalived.conf");if _,err=m.Runner.Run(ctx,"/usr/bin/dnf","-y","remove","keepalived");err!=nil{return err}};return os.Remove(path)}
func(m Manager)applyVRRP(ctx context.Context,serviceID string,n model.NetworkSpec,plan model.Plan)error{pin,err:=findPin(plan,"vrrp","keepalived");if err!=nil{return err};d:=packageutil.DNF{Runner:m.Runner};current,err:=d.RepositoryDigest(ctx,pin.RepositoryID);if err!=nil{return err};if current!=pin.RepositoryDigest{return errors.New("Keepalived repository configuration drifted after plan confirmation")};if err=d.InstallExactFromRepos(ctx,[]string{pin.RepositoryID},pin.ResolvedVersion);err!=nil{return err};stageDir:="/run/layersentryd/vip";if err=os.MkdirAll(stageDir,0700);err!=nil{return err};staged:=filepath.Join(stageDir,serviceID+".conf");conf:=renderKeepalived(serviceID,n);if err=filesystem.AtomicWrite(staged,[]byte(conf),0600,stageDir);err!=nil{return err};if _,err=m.Runner.Run(ctx,"/usr/bin/install","--mode=0600","--owner=root","--group=root",staged,"/etc/keepalived/keepalived.conf");err!=nil{return err};defer os.Remove(staged);args:=append([]string{serviceID},n.VIP.Peers...);if _,err=m.Runner.Run(ctx,vipexec.VRRPFirewallAdd,args...);err!=nil{return err};_,err=m.Runner.Run(ctx,"/usr/bin/systemctl","enable","--now","keepalived.service");return err}
func renderKeepalived(serviceID string,n model.NetworkSpec)string{v:=n.VIP;var b strings.Builder;fmt.Fprintf(&b,"global_defs {\n    enable_script_security\n}\n\nvrrp_instance %s {\n    state %s\n    interface %s\n    virtual_router_id %d\n    priority %d\n    advert_int 1\n    unicast_src_ip %s\n    unicast_peer {\n",instanceName(serviceID),v.State,v.Interface,v.VirtualRouterID,v.Priority,n.ListenAddress);for _,peer:=range v.Peers{fmt.Fprintf(&b,"        %s\n",peer)};fmt.Fprintf(&b,"    }\n    virtual_ipaddress {\n        %s/%d dev %s\n    }\n}\n",v.Address,v.PrefixLength,v.Interface);return b.String()}
func instanceName(serviceID string)string{s:=sha256.Sum256([]byte(serviceID));return "LS_"+strings.ToUpper(hex.EncodeToString(s[:6]))}
func findPin(plan model.Plan,purpose,pkg string)(model.PlatformPackagePin,error){for _,p:=range plan.PlatformPackages{if p.Purpose==purpose&&p.Package==pkg&&p.ResolvedVersion!=""&&p.RepositoryID!=""&&p.RepositoryDigest!=""{return p,nil}};return model.PlatformPackagePin{},errors.New("required platform package pin missing from immutable plan")}
func(m Manager)ensureStateRoot()error{if m.StateRoot==""{m.StateRoot="/var/lib/layersentryd/state/vip"};return os.MkdirAll(m.StateRoot,0700)}
func readState(path string)(state,bool,error){fi,err:=os.Lstat(path);if errors.Is(err,os.ErrNotExist){return state{},false,nil};if err!=nil{return state{},false,err};if fi.Mode()&os.ModeSymlink!=0||!fi.Mode().IsRegular()||fi.Size()>64<<10{return state{},false,errors.New("unsafe VIP state record")};b,err:=os.ReadFile(path);if err!=nil{return state{},false,err};var s state;if err=json.Unmarshal(b,&s);err!=nil{return state{},false,err};return s,true,nil}
