package postgresql

import (
 "bytes"
 "context"
 "crypto/sha256"
 "encoding/hex"
 "errors"
 "fmt"
 "io"
 "os"
 "os/user"
 "path/filepath"
 "regexp"
 "strconv"
 "strings"
 "time"

 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/executor"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/filesystem"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/packageutil"
)

var majorRE=regexp.MustCompile(`^(16|17)$`)
type SecretGetter interface{Get(string)([]byte,error)}
type Provider struct{Runner executor.Runner; DNF packageutil.DNF; Secrets SecretGetter}
func New(r executor.Runner,s SecretGetter)*Provider{return &Provider{Runner:r,DNF:packageutil.DNF{Runner:r},Secrets:s}}
func(p *Provider)ID()string{return "postgresql"}
func(p *Provider)Category()model.Category{return model.CategoryDatabase}
func(p *Provider)Validate(_ context.Context,r model.ServiceRequest)error{if r.Category!=model.CategoryDatabase{return errors.New("postgresql category must be database")};if !majorRE.MatchString(r.ReleaseLine){return errors.New("supported PostgreSQL release lines: 16,17")};if r.Topology=="standalone"&&r.SecretRefs["admin_password"]==""{return errors.New("postgresql admin_password secret reference is required")};for _,s:=range r.Storage{if s.Purpose=="database-data"&&s.MountPoint!="/var/lib/pgsql/"+r.ReleaseLine+"/data"{return fmt.Errorf("PostgreSQL database-data mount must be /var/lib/pgsql/%s/data so the vendor systemd unit owns the same PGDATA",r.ReleaseLine)}};if r.Topology=="cluster"{switch r.Cluster.Role{case "primary","standby":default:return errors.New("postgresql cluster role must be primary or standby")}};return nil}
func(p *Provider)ResolveVersion(ctx context.Context,r model.ServiceRequest)(string,error){return p.DNF.ResolveLatest(ctx,"postgresql"+r.ReleaseLine+"-server")}
func(p *Provider)Plan(_ context.Context,r model.ServiceRequest,resolved string)(model.Plan,error){steps:=[]model.PlanStep{{Name:"packages",Action:"install exact official PostgreSQL server package "+resolved},{Name:"storage",Action:"prepare requested data/WAL/log mounts"},{Name:"initialize",Action:"initialize database cluster with SCRAM host authentication"},{Name:"configure",Action:"write provider-owned PostgreSQL listener/HBA/log configuration"},{Name:"firewall",Action:"open listener only to requested CIDRs"},{Name:"service",Action:"enable and start postgresql-"+r.ReleaseLine},{Name:"health",Action:"pg_isready plus local SQL/version validation"}};for _,s:=range r.Storage{if s.Format{steps=append([]model.PlanStep{{Name:"format",Action:"format "+s.Device+" as "+s.Filesystem,Destructive:true,Detail:"THIS DEVICE WILL BE FORMATTED"}},steps...)}};raw:=fmt.Sprintf("%s|%s|%s|%v",r.ServiceID,r.Provider,resolved,steps);sum:=sha256.Sum256([]byte(raw));return model.Plan{ID:r.OperationID,ServiceID:r.ServiceID,Provider:p.ID(),ResolvedVersion:resolved,Digest:hex.EncodeToString(sum[:]),CreatedAt:time.Now().UTC(),Request:r,Steps:steps},nil}
func(p *Provider)Install(ctx context.Context,_ model.Operation,plan model.Plan)error{return p.DNF.InstallExact(ctx,plan.ResolvedVersion)}
func(p *Provider)Configure(context.Context,model.Operation,model.Plan)error{return nil}
func(p *Provider)Initialize(ctx context.Context,_ model.Operation,plan model.Plan)error{major:=extractMajor(plan.ResolvedVersion);if major==""{return errors.New("cannot derive PostgreSQL major")};if p.Secrets==nil{return errors.New("secret store unavailable")};dataDir:=dataDir(plan.Request,major);if err:=prepareOwnedDir(dataDir,"postgres",0700);err!=nil{return err};if wal:=storagePath(plan.Request,"database-wal");wal!=""{if err:=prepareOwnedDir(wal,"postgres",0700);err!=nil{return err}};if logs:=storagePath(plan.Request,"database-logs");logs!=""{if err:=prepareOwnedDir(logs,"postgres",0700);err!=nil{return err}};if existing,err:=os.ReadFile(filepath.Join(dataDir,"PG_VERSION"));err==nil{if strings.TrimSpace(string(existing))!=major{return errors.New("existing PostgreSQL data directory major does not match requested release")};if err=writePostgresConfig(dataDir,plan.Request);err!=nil{return err};return writeHBA(dataDir,plan.Request.Network.AllowedCIDRs)}else if !errors.Is(err,os.ErrNotExist){return err};ref:=plan.Request.SecretRefs["admin_password"];secret,err:=p.Secrets.Get(ref);if err!=nil{return err};defer zero(secret);pw,err:=os.CreateTemp("/run/layersentryd","pgpw-*");if err!=nil{return err};pwPath:=pw.Name();defer os.Remove(pwPath);if err=pw.Chmod(0640);err!=nil{pw.Close();return err};if _,err=pw.Write(append(secret,'\n'));err!=nil{pw.Close();return err};if err=pw.Close();err!=nil{return err};if err=chgrpTo(pwPath,"postgres");err!=nil{return err};bin:="/usr/pgsql-"+major+"/bin/initdb";args:=[]string{"-D",dataDir,"--username=postgres","--pwfile="+pwPath,"--auth-local=peer","--auth-host=scram-sha-256","--encoding=UTF8"};if wal:=storagePath(plan.Request,"database-wal");wal!=""{args=append(args,"--waldir="+wal)};runArgs:=append([]string{"-u","postgres","--",bin},args...);if _,err=p.Runner.Run(ctx,"/usr/sbin/runuser",runArgs...);err!=nil{return err};if err=writePostgresConfig(dataDir,plan.Request);err!=nil{return err};return writeHBA(dataDir,plan.Request.Network.AllowedCIDRs)}
func(p *Provider)Join(context.Context,model.Operation,model.Plan)error{return errors.New("real multi-node PostgreSQL join is not enabled under the one-VM acceptance envelope")}
func(p *Provider)Health(ctx context.Context,st model.ServiceState)(model.HealthResult,error){major:=st.ReleaseLine;checks:=map[string]string{};args:=[]string{"-q","-p",strconv.Itoa(st.Network.Port)};if st.Network.ListenAddress!=""{args=append(args,"-h",st.Network.ListenAddress)};if _,err:=p.Runner.Run(ctx,"/usr/pgsql-"+major+"/bin/pg_isready",args...);err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:err.Error()},nil};checks["pg_isready"]="ok";r,err:=p.Runner.Run(ctx,"/usr/sbin/runuser","-u","postgres","--","/usr/pgsql-"+major+"/bin/psql","-XAtq","-p",strconv.Itoa(st.Network.Port),"-d","postgres","-c","SELECT current_setting('server_version')");if err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:err.Error()},nil};checks["sql_query"]="ok";checks["version"]=strings.TrimSpace(r.Stdout);return model.HealthResult{Healthy:true,Version:strings.TrimSpace(r.Stdout),Checks:checks},nil}
func(p *Provider)Upgrade(ctx context.Context,op model.Operation,plan model.Plan)error{if extractMajor(plan.ResolvedVersion)==""{return errors.New("upgrade target is not an allowed PostgreSQL release line")};if err:=p.Install(ctx,op,plan);err!=nil{return err};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart","postgresql-"+extractMajor(plan.ResolvedVersion)+".service");return err}
func(p *Provider)Repair(ctx context.Context,_ model.Operation,plan model.Plan)error{major:=extractMajor(plan.ResolvedVersion);if major==""{return errors.New("unknown major")};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart","postgresql-"+major+".service");return err}
func(p *Provider)Backup(ctx context.Context,op model.Operation,st model.ServiceState)(model.BackupRecord,error){dir:="/var/lib/layersentryd/backups/"+st.ID;if err:=prepareOwnedDir(dir,"postgres",0700);err!=nil{return model.BackupRecord{},err};file:=filepath.Join(dir,op.ID+"-pg_dumpall.sql");if _,err:=p.Runner.Run(ctx,"/usr/sbin/runuser","-u","postgres","--","/usr/pgsql-"+st.ReleaseLine+"/bin/pg_dumpall","--clean","--if-exists","--file="+file);err!=nil{return model.BackupRecord{},err};sum,size,err:=verifyBackup(file);if err!=nil{return model.BackupRecord{},err};return model.BackupRecord{ID:op.ID,ServiceID:st.ID,Provider:p.ID(),Path:file,SHA256:sum,SizeBytes:size,Verified:true,CreatedAt:time.Now().UTC()},nil}
func(p *Provider)Restore(ctx context.Context,_ model.Operation,st model.ServiceState,b model.BackupRecord)error{if !b.Verified||b.ServiceID!=st.ID||b.Provider!=p.ID(){return errors.New("backup identity/provider verification failed")};expectedRoot:=filepath.Join("/var/lib/layersentryd/backups",st.ID);clean:=filepath.Clean(b.Path);rel,err:=filepath.Rel(expectedRoot,clean);if err!=nil||rel==".."||strings.HasPrefix(rel,".."+string(filepath.Separator)){return errors.New("backup path outside service backup root")};fi,err:=os.Lstat(clean);if err!=nil{return err};if fi.Mode()&os.ModeSymlink!=0||!fi.Mode().IsRegular(){return errors.New("backup file is not a safe regular file")};sum,size,err:=inspectBackup(clean);if err!=nil{return err};if sum!=b.SHA256||size!=b.SizeBytes{return errors.New("backup checksum/size verification failed")};_,err=p.Runner.Run(ctx,"/usr/sbin/runuser","-u","postgres","--","/usr/pgsql-"+st.ReleaseLine+"/bin/psql","-X","-v","ON_ERROR_STOP=1","-p",strconv.Itoa(st.Network.Port),"-d","postgres","--file="+clean);return err}
func(p *Provider)Uninstall(ctx context.Context,_ model.Operation,st model.ServiceState,destroyData bool)error{if destroyData{return errors.New("destructive data removal requires a separate implementation/authorization")};_,_=p.Runner.Run(ctx,"/usr/bin/systemctl","disable","--now","postgresql-"+st.ReleaseLine+".service");return p.DNF.Remove(ctx,"postgresql"+st.ReleaseLine+"-server")}
func(p *Provider)ResidueAudit(ctx context.Context,st model.ServiceState)(map[string]string,error){out:=map[string]string{};r,_:=p.Runner.Run(ctx,"/usr/bin/rpm","-q","postgresql"+st.ReleaseLine+"-server");if r.ExitCode==0{out["rpm"]="present"}else{out["rpm"]="absent"};r,_=p.Runner.Run(ctx,"/usr/bin/systemctl","is-active","postgresql-"+st.ReleaseLine+".service");if r.ExitCode==0{out["service"]="active"}else{out["service"]="inactive"};out["customer_data"]="preserved";return out,nil}
func extractMajor(nevra string)string{for _,m:=range []string{"16","17"}{if strings.Contains(nevra,"postgresql"+m+"-server"){return m}};return ""}
func dataDir(r model.ServiceRequest,major string)string{for _,s:=range r.Storage{if s.Purpose=="database-data"{return s.MountPoint}};return "/var/lib/pgsql/"+major+"/data"}
func storagePath(r model.ServiceRequest,purpose string)string{for _,s:=range r.Storage{if s.Purpose==purpose{return s.MountPoint}};return ""}
func prepareOwnedDir(path,name string,mode os.FileMode)error{if err:=os.MkdirAll(path,mode);err!=nil{return err};if err:=os.Chmod(path,mode);err!=nil{return err};return chownTo(path,name)}
func chownTo(path,name string)error{u,err:=user.Lookup(name);if err!=nil{return err};uid,err:=strconv.Atoi(u.Uid);if err!=nil{return err};gid,err:=strconv.Atoi(u.Gid);if err!=nil{return err};return os.Chown(path,uid,gid)}
func chgrpTo(path,name string)error{u,err:=user.Lookup(name);if err!=nil{return err};gid,err:=strconv.Atoi(u.Gid);if err!=nil{return err};return os.Chown(path,-1,gid)}
func writePostgresConfig(dir string,r model.ServiceRequest)error{path:=filepath.Join(dir,"postgresql.conf");old,err:=os.ReadFile(path);if err!=nil{return err};listen:=r.Network.ListenAddress;if listen==""{listen="localhost"};block:=fmt.Sprintf("\n# LayerSentry managed settings\nlisten_addresses = '%s'\nport = %d\npassword_encryption = 'scram-sha-256'\n",strings.ReplaceAll(listen,"'",""),r.Network.Port);if logs:=storagePath(r,"database-logs");logs!=""{block+=fmt.Sprintf("logging_collector = on\nlog_directory = '%s'\nlog_filename = 'postgresql-%%Y-%%m-%%d_%%H%%M%%S.log'\n",strings.ReplaceAll(logs,"'",""))};return filesystem.AtomicWrite(path,append(old,[]byte(block)...),0600,dir)}
func writeHBA(dir string,cidrs []string)error{var b strings.Builder;b.WriteString("# LayerSentry managed pg_hba.conf\nlocal all all peer\n");for _,c:=range cidrs{fmt.Fprintf(&b,"host all all %s scram-sha-256\n",c)};return filesystem.AtomicWrite(filepath.Join(dir,"pg_hba.conf"),[]byte(b.String()),0600,dir)}
func verifyBackup(path string)(string,int64,error){sum,size,err:=inspectBackup(path);if err!=nil{return "",0,err};sidecar:=path+".sha256";if err=filesystem.AtomicWrite(sidecar,[]byte(sum+"  "+filepath.Base(path)+"\n"),0600,filepath.Dir(path));err!=nil{return "",0,err};if err=chownTo(sidecar,"postgres");err!=nil{return "",0,err};return sum,size,nil}
func inspectBackup(path string)(string,int64,error){st,err:=os.Lstat(path);if err!=nil{return "",0,err};if st.Mode()&os.ModeSymlink!=0||!st.Mode().IsRegular()||st.Size()<128{return "",0,errors.New("PostgreSQL backup is empty or unsafe")};f,err:=os.Open(path);if err!=nil{return "",0,err};defer f.Close();head:=make([]byte,64<<10);n,_:=f.Read(head);if _,err=f.Seek(0,0);err!=nil{return "",0,err};if !bytes.Contains(head[:n],[]byte("PostgreSQL database cluster dump")){return "",0,errors.New("PostgreSQL backup structure verification failed")};h:=sha256.New();if _,err=io.Copy(h,f);err!=nil{return "",0,err};return hex.EncodeToString(h.Sum(nil)),st.Size(),nil}
func zero(b []byte){for i:=range b{b[i]=0}}
