package config

import (
 "crypto/sha256"
 "encoding/hex"
 "encoding/json"
 "errors"
 "fmt"
 "io"
 "net"
 "path/filepath"
 "regexp"
 "strings"

 "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
)

var uuidRE=regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`)
var secretRE=regexp.MustCompile(`^secret://[0-9a-f]{32}$`)
var nameRE=regexp.MustCompile(`^[a-z][a-z0-9_-]{0,63}$`)
var lvmNameRE=regexp.MustCompile(`^ls_[a-z0-9_]{1,48}$`)
var lvmSizeRE=regexp.MustCompile(`^([1-9][0-9]*[MGT]|100%FREE)$`)
var ifaceRE=regexp.MustCompile(`^[A-Za-z0-9_.:-]{1,32}$`)
var tlsFingerprintRE=regexp.MustCompile(`^[0-9a-f]{64}$`)
func DecodeStrict(data []byte)(model.ServiceRequest,error){var req model.ServiceRequest;dec:=json.NewDecoder(strings.NewReader(string(data)));dec.DisallowUnknownFields();if err:=dec.Decode(&req);err!=nil{return req,fmt.Errorf("decode request: %w",err)};var extra any;if err:=dec.Decode(&extra);err!=io.EOF{return req,errors.New("multiple JSON values are not allowed")};if err:=Validate(req);err!=nil{return req,err};return req,nil}
func Validate(req model.ServiceRequest)error{if req.SchemaVersion!=1{return fmt.Errorf("unsupported schema_version %d",req.SchemaVersion)};for name,v:=range map[string]string{"request_id":req.RequestID,"service_id":req.ServiceID,"operation_id":req.OperationID}{if !uuidRE.MatchString(v){return fmt.Errorf("%s must be a UUID",name)}};if strings.TrimSpace(req.IdempotencyKey)==""||len(req.IdempotencyKey)>256||strings.ContainsAny(req.IdempotencyKey,"\x00\r\n"){return errors.New("idempotency_key is required, bounded and single-line")};if !nameRE.MatchString(req.Provider){return errors.New("provider name is invalid")};if strings.TrimSpace(req.ReleaseLine)==""||len(req.ReleaseLine)>64||strings.ContainsAny(req.ReleaseLine,"\x00\r\n/\\"){return errors.New("release_line is invalid")};if req.ResolvedVersion!=""{return errors.New("resolved_version is server-owned and must be empty in service intent")};if req.Category!=model.CategoryDatabase&&req.Category!=model.CategoryApplication{return errors.New("category must be database or application")};if req.Topology!="standalone"&&req.Topology!="cluster"{return errors.New("topology must be standalone or cluster")};if err:=validateMaintenance(req.Maintenance);err!=nil{return err};if req.Backup.Retention<0||req.Backup.Retention>3650{return errors.New("backup retention outside 0..3650")};if req.Backup.Enabled&&req.Backup.Retention<1{return errors.New("enabled backup requires retention >=1")};if !req.Backup.Enabled&&(req.Backup.Schedule!=""||req.Backup.Retention!=0){return errors.New("disabled backup may not carry schedule/retention")};if req.Backup.Schedule!=""{switch req.Backup.Schedule{case "daily","weekly","monthly":default:return errors.New("unsupported backup schedule")}};if err:=validateNetwork(req);err!=nil{return err};seenDevices:=map[string]bool{};seenMounts:=map[string]bool{};for _,s:=range req.Storage{if err:=validateStorageAssignment(s,seenDevices,seenMounts);err!=nil{return err}};if err:=validateLVM(req.LVM,seenDevices,seenMounts);err!=nil{return err};for k,v:=range req.SecretRefs{if !nameRE.MatchString(k)||!secretRE.MatchString(v){return fmt.Errorf("secret_refs must contain named canonical secret:// references")}};return validateCluster(req)}
func validateNetwork(req model.ServiceRequest)error{n:=req.Network;if n.Port<0||n.Port>65535{return errors.New("network.port outside 0..65535")};if n.Port==0&&(n.ListenAddress!=""||len(n.AllowedCIDRs)>0||n.VIP.Mode!=""){return errors.New("network port 0 is valid only for non-listening providers with no address/CIDRs/VIP")};if n.ListenAddress!=""&&net.ParseIP(n.ListenAddress)==nil{return errors.New("invalid listen_address")};seenCIDR:=map[string]bool{};for _,cidr:=range n.AllowedCIDRs{_,nw,err:=net.ParseCIDR(cidr);if err!=nil{return fmt.Errorf("invalid allowed CIDR %q",cidr)};canon:=nw.String();if seenCIDR[canon]{return fmt.Errorf("duplicate allowed CIDR %q",cidr)};seenCIDR[canon]=true};return validateVIP(req)}
func validateVIP(req model.ServiceRequest)error{v:=req.Network.VIP;if v.Mode==""{if v.Address!=""||v.PrefixLength!=0||v.Interface!=""||v.State!=""||v.VirtualRouterID!=0||v.Priority!=0||len(v.Peers)>0{return errors.New("VIP fields require vip.mode")};return nil};ip:=net.ParseIP(v.Address);if ip==nil||ip.To4()==nil||ip.String()!=v.Address{return errors.New("VIP address must be a canonical IPv4 address")};if v.PrefixLength<1||v.PrefixLength>32{return errors.New("VIP prefix_length outside 1..32")};if !ifaceRE.MatchString(v.Interface){return errors.New("VIP interface is invalid")};if req.Network.ListenAddress!=""&&v.Address==net.ParseIP(req.Network.ListenAddress).String(){return errors.New("VIP address must differ from the node listen_address")};switch v.Mode{case "secondary":if v.State!=""||v.VirtualRouterID!=0||v.Priority!=0||len(v.Peers)>0{return errors.New("secondary VIP does not accept VRRP fields")};case "vrrp":if req.Topology!="cluster"{return errors.New("VRRP VIP requires cluster topology")};if v.State!="MASTER"&&v.State!="BACKUP"{return errors.New("VRRP state must be MASTER or BACKUP")};if v.VirtualRouterID<1||v.VirtualRouterID>255{return errors.New("VRRP virtual_router_id outside 1..255")};if v.Priority<1||v.Priority>254{return errors.New("VRRP priority outside 1..254")};if len(v.Peers)<1||len(v.Peers)>16{return errors.New("VRRP requires 1..16 unicast peers")};seen:=map[string]bool{};for _,peer:=range v.Peers{p:=net.ParseIP(peer);if p==nil||p.To4()==nil||p.String()!=peer{return fmt.Errorf("invalid VRRP peer %q",peer)};if seen[peer]{return fmt.Errorf("duplicate VRRP peer %q",peer)};seen[peer]=true;if req.Network.ListenAddress!=""&&peer==net.ParseIP(req.Network.ListenAddress).String(){return errors.New("VRRP peer may not equal local listen_address")};if peer==v.Address{return errors.New("VRRP peer may not equal VIP address")}};default:return errors.New("VIP mode must be secondary or vrrp")};return nil}
func validateStorageAssignment(s model.StorageAssignment,seenDevices,seenMounts map[string]bool)error{if !strings.HasPrefix(s.Device,"/dev/disk/by-"){return fmt.Errorf("device must use stable /dev/disk/by-* identity: %q",s.Device)};if seenDevices[s.Device]{return fmt.Errorf("duplicate storage device %q",s.Device)};seenDevices[s.Device]=true;clean:=filepath.Clean(s.MountPoint);if !allowedMount(clean){return fmt.Errorf("unsafe mount point %q",s.MountPoint)};if clean!=s.MountPoint{return fmt.Errorf("mount point must be canonical: %q",s.MountPoint)};if seenMounts[clean]{return fmt.Errorf("duplicate mount point %q",clean)};seenMounts[clean]=true;if s.Format&&!s.ConfirmFormat{return fmt.Errorf("format requires confirm_format for %q",s.Device)};if err:=validateFilesystemPurpose(s.Filesystem,s.Purpose);err!=nil{return err};return nil}
func validateLVM(groups []model.LVMVolumeGroup,seenDevices,seenMounts map[string]bool)error{seenVG:=map[string]bool{};for _,g:=range groups{if !lvmNameRE.MatchString(g.Name){return fmt.Errorf("LVM volume-group name %q must use ls_ prefix",g.Name)};if seenVG[g.Name]{return fmt.Errorf("duplicate LVM volume group %q",g.Name)};seenVG[g.Name]=true;if len(g.Devices)<1||len(g.Devices)>16{return fmt.Errorf("LVM volume group %s requires 1..16 devices",g.Name)};if g.InitializePVs&&!g.ConfirmPVInitialize{return fmt.Errorf("LVM PV initialization for %s requires confirm_pv_initialize",g.Name)};if !g.InitializePVs&&g.ConfirmPVInitialize{return fmt.Errorf("confirm_pv_initialize is invalid when initialize_pvs is false for %s",g.Name)};for _,d:=range g.Devices{if !strings.HasPrefix(d,"/dev/disk/by-"){return fmt.Errorf("LVM PV must use stable /dev/disk/by-* identity: %q",d)};if seenDevices[d]{return fmt.Errorf("storage device %q is assigned more than once",d)};seenDevices[d]=true};if len(g.LogicalVolumes)<1||len(g.LogicalVolumes)>32{return fmt.Errorf("LVM volume group %s requires 1..32 logical volumes",g.Name)};seenLV:=map[string]bool{};freeSeen:=false;for i,lv:=range g.LogicalVolumes{if !lvmNameRE.MatchString(lv.Name){return fmt.Errorf("LVM logical-volume name %q must use ls_ prefix",lv.Name)};if seenLV[lv.Name]{return fmt.Errorf("duplicate LVM logical volume %q in %s",lv.Name,g.Name)};seenLV[lv.Name]=true;if !lvmSizeRE.MatchString(lv.Size){return fmt.Errorf("invalid LVM size %q; use integer M/G/T or 100%%FREE",lv.Size)};if lv.Size=="100%FREE"{if freeSeen||i!=len(g.LogicalVolumes)-1{return errors.New("100%FREE may be used once and only by the final logical volume")};freeSeen=true};clean:=filepath.Clean(lv.MountPoint);if !allowedMount(clean)||clean!=lv.MountPoint{return fmt.Errorf("unsafe LVM mount point %q",lv.MountPoint)};if seenMounts[clean]{return fmt.Errorf("duplicate mount point %q",clean)};seenMounts[clean]=true;if lv.Format&&!lv.ConfirmFormat{return fmt.Errorf("LVM format requires confirm_format for %s/%s",g.Name,lv.Name)};if err:=validateFilesystemPurpose(lv.Filesystem,lv.Purpose);err!=nil{return err}}};return nil}
func validateFilesystemPurpose(filesystem,purpose string)error{switch filesystem{case "xfs","ext4","":default:return fmt.Errorf("unsupported filesystem %q",filesystem)};switch purpose{case "database-data","database-wal","database-logs","database-backup","application-data","application-logs","cache","temporary":default:return fmt.Errorf("unsupported storage purpose %q",purpose)};return nil}
func validateCluster(req model.ServiceRequest)error{c:=req.Cluster;if req.Topology=="standalone"{if len(c.Peers)>0||c.Role!=""||c.JoinTokenRef!=""||c.EnrollmentPeer!=""||len(c.PeerTLSFingerprints)>0||c.ManagementPort!=0||c.MaxClockSkewSeconds!=0{return errors.New("cluster fields are not allowed for standalone topology")};return nil};if strings.TrimSpace(c.Role)==""||len(c.Role)>32||strings.ContainsAny(c.Role,"\x00\r\n/\\"){return errors.New("cluster role is required and bounded")};if c.ManagementPort<0||c.ManagementPort>65535{return errors.New("cluster management_port outside 1..65535")};if c.MaxClockSkewSeconds<0||c.MaxClockSkewSeconds>600||(c.MaxClockSkewSeconds>0&&c.MaxClockSkewSeconds<30){return errors.New("cluster max_clock_skew_seconds must be 30..600 when set")};seen:=map[string]bool{};for _,peer:=range c.Peers{ip:=net.ParseIP(peer);if ip==nil{return fmt.Errorf("invalid cluster peer %q",peer)};canon:=ip.String();if canon!=peer{return fmt.Errorf("cluster peer must be canonical IP %q",peer)};if seen[canon]{return fmt.Errorf("duplicate cluster peer %q",peer)};seen[canon]=true;if req.Network.ListenAddress!=""&&canon==net.ParseIP(req.Network.ListenAddress).String(){return errors.New("cluster peer may not equal this node listen address")}};for peer,pin:=range c.PeerTLSFingerprints{ip:=net.ParseIP(peer);if ip==nil||ip.String()!=peer{return fmt.Errorf("cluster TLS fingerprint key must be a canonical peer IP %q",peer)};if !seen[peer]{return fmt.Errorf("cluster TLS fingerprint references undeclared peer %q",peer)};if !tlsFingerprintRE.MatchString(pin){return fmt.Errorf("cluster TLS fingerprint for %q must be lowercase SHA-256 hex",peer)}};if c.JoinTokenRef!=""&&!secretRE.MatchString(c.JoinTokenRef){return errors.New("cluster join token must be a secret reference")};if c.EnrollmentPeer!=""{ip:=net.ParseIP(c.EnrollmentPeer);if ip==nil||ip.String()!=c.EnrollmentPeer{return errors.New("cluster enrollment_peer must be a canonical IP")};if !seen[c.EnrollmentPeer]{return errors.New("cluster enrollment_peer must be present in peers")};if c.JoinTokenRef==""{return errors.New("cluster enrollment_peer requires join_token_ref")};if !tlsFingerprintRE.MatchString(c.PeerTLSFingerprints[c.EnrollmentPeer]){return errors.New("cluster enrollment_peer requires its pinned TLS fingerprint")}}else if c.JoinTokenRef!=""{return errors.New("cluster join_token_ref requires enrollment_peer")};return nil}
func validateMaintenance(p model.MaintenancePolicy)error{switch p.Mode{case "manual","daily","weekly","monthly","notify-only":default:return fmt.Errorf("unsupported maintenance mode %q",p.Mode)};if p.AutoPatch&&!p.ReleaseLineLocked{return errors.New("auto_patch requires release_line_locked")};if p.Mode=="weekly"&&p.Day!=""{valid:=map[string]bool{"Monday":true,"Tuesday":true,"Wednesday":true,"Thursday":true,"Friday":true,"Saturday":true,"Sunday":true};if !valid[p.Day]{return errors.New("invalid weekly maintenance day")}};if p.Window!=""{var h1,m1,h2,m2 int;if _,err:=fmt.Sscanf(p.Window,"%d:%d-%d:%d",&h1,&m1,&h2,&m2);err!=nil||h1>23||h2>23||m1>59||m2>59||h1<0||h2<0||m1<0||m2<0||(h1==h2&&m1==m2){return errors.New("maintenance window must be a non-empty HH:MM-HH:MM range")}};return nil}
func allowedMount(path string)bool{if !filepath.IsAbs(path)||filepath.Clean(path)!=path{return false};for _,root:=range []string{"/var/lib/pgsql","/var/lib/mysql","/var/lib/redis","/var/lib/valkey","/var/lib/layersentryd/apps","/var/lib/tomcat","/var/www/html","/srv","/data","/opt/layersentry-data","/var/log/layersentry-services"}{if path==root||strings.HasPrefix(path,root+string(filepath.Separator)){return true}};return false}
func CanonicalDigest(req model.ServiceRequest)(string,error){b,err:=json.Marshal(req);if err!=nil{return "",err};s:=sha256.Sum256(b);return hex.EncodeToString(s[:]),nil}
func PlanDigest(plan model.Plan)(string,error){plan.Digest="";b,err:=json.Marshal(plan);if err!=nil{return "",err};s:=sha256.Sum256(b);return hex.EncodeToString(s[:]),nil}
