package ansiblerunner

import (
    "context"
    "encoding/json"
    "errors"
    "fmt"
    "os"
    "path/filepath"
    "syscall"

    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/ansibleexec"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/filesystem"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/storageplan"
)

const DefaultRuntimeRoot = "/run/layersentryd/ansible"
type SecretGetter interface { Get(string) ([]byte, error) }
type Runner struct { Exec ansibleexec.Client; Secrets SecretGetter; RuntimeRoot string }
type varsFile struct {
    Schema int `json:"layersentry_schema"`; Action string `json:"layersentry_action"`; OperationID string `json:"layersentry_operation_id"`; ServiceID string `json:"layersentry_service_id"`; Provider string `json:"layersentry_provider"`; ServiceUnit string `json:"layersentry_service_unit"`; PlanDigest string `json:"layersentry_plan_digest"`; Request model.ServiceRequest `json:"layersentry_request"`; ResolvedVersion string `json:"layersentry_resolved_version"`; RepositoryID string `json:"layersentry_repository_id"`; RepositoryDigest string `json:"layersentry_repository_digest"`; PlatformPackages []model.PlatformPackagePin `json:"layersentry_platform_packages"`; Paths map[string]string `json:"layersentry_paths"`; SecretsB64 map[string][]byte `json:"layersentry_secrets_b64"`; VRRPKeepalivedNEVRA string `json:"layersentry_vrrp_keepalived_nevra,omitempty"`; VRRPKeepalivedRepository string `json:"layersentry_vrrp_keepalived_repo,omitempty"`; DestroyData bool `json:"layersentry_destroy_data"`
}
func New(exec ansibleexec.Client,secrets SecretGetter)*Runner{return &Runner{Exec:exec,Secrets:secrets,RuntimeRoot:DefaultRuntimeRoot}}
func(r *Runner)RunPlan(ctx context.Context,action string,op model.Operation,plan model.Plan)error{if plan.ID!=op.ID||plan.ServiceID!=op.ServiceID||plan.Request.OperationID!=op.ID{return errors.New("Ansible plan/operation identity mismatch")};v,secretBytes,err:=r.planVars(action,op,plan);if err!=nil{return err};defer wipeMany(secretBytes);return r.invoke(ctx,action,op.ID,v)}
func(r *Runner)RunState(ctx context.Context,action string,op model.Operation,st model.ServiceState,destroyData bool)error{if st.ID!=op.ServiceID{return errors.New("Ansible state/operation identity mismatch")};req:=requestFromState(op,st);paths,err:=pathsForRequest(req);if err!=nil{return err};unit,err:=serviceUnit(st.Provider,st.ReleaseLine);if err!=nil{return err};secretsB64,secretBytes,err:=r.resolveSecrets(st.SecretRefs);if err!=nil{return err};defer wipeMany(secretBytes);v:=varsFile{Schema:1,Action:action,OperationID:op.ID,ServiceID:st.ID,Provider:st.Provider,ServiceUnit:unit,PlanDigest:st.PlanDigest,Request:req,ResolvedVersion:st.ResolvedVersion,RepositoryID:st.RepositoryID,RepositoryDigest:st.RepositoryDigest,PlatformPackages:append([]model.PlatformPackagePin{},st.PlatformPackages...),Paths:paths,SecretsB64:secretsB64,DestroyData:destroyData};setVRRPPin(&v);return r.invoke(ctx,action,op.ID,v)}
func(r *Runner)planVars(action string,op model.Operation,plan model.Plan)(varsFile,[][]byte,error){paths,err:=pathsForRequest(plan.Request);if err!=nil{return varsFile{},nil,err};unit,err:=serviceUnit(plan.Provider,plan.Request.ReleaseLine);if err!=nil{return varsFile{},nil,err};secretsB64,secretBytes,err:=r.resolveSecrets(plan.Request.SecretRefs);if err!=nil{return varsFile{},nil,err};v:=varsFile{Schema:1,Action:action,OperationID:op.ID,ServiceID:plan.ServiceID,Provider:plan.Provider,ServiceUnit:unit,PlanDigest:plan.Digest,Request:plan.Request,ResolvedVersion:plan.ResolvedVersion,RepositoryID:plan.RepositoryID,RepositoryDigest:plan.RepositoryDigest,PlatformPackages:append([]model.PlatformPackagePin{},plan.PlatformPackages...),Paths:paths,SecretsB64:secretsB64};setVRRPPin(&v);return v,secretBytes,nil}
func(r *Runner)resolveSecrets(refs map[string]string)(map[string][]byte,[][]byte,error){if len(refs)==0{return map[string][]byte{},nil,nil};if r.Secrets==nil{return nil,nil,errors.New("Ansible secret resolver unavailable")};out:=make(map[string][]byte,len(refs));var owned [][]byte;for name,ref:=range refs{raw,err:=r.Secrets.Get(ref);if err!=nil{wipeMany(owned);return nil,nil,fmt.Errorf("resolve Ansible secret %s: %w",name,err)};if len(raw)==0||len(raw)>64<<10{wipe(raw);wipeMany(owned);return nil,nil,fmt.Errorf("Ansible secret %s length outside allowed bounds",name)};out[name]=raw;owned=append(owned,raw)};return out,owned,nil}
func(r *Runner)invoke(ctx context.Context,action,operationID string,v varsFile)error{root:=r.RuntimeRoot;if root==""{root=DefaultRuntimeRoot};if err:=ensureRuntimeRoot(root);err!=nil{return err};name:=operationID+"-"+action+".json";path:=filepath.Join(root,name);payload,err:=json.Marshal(v);if err!=nil{return err};defer wipe(payload);if err=filesystem.AtomicWrite(path,payload,0600,root);err!=nil{return err};defer func(){_ = os.Remove(path)}();res,err:=r.Exec.Run(ctx,action,path);if err!=nil{return fmt.Errorf("Ansible %s failed with exit=%d; raw Ansible output is intentionally excluded from durable operation errors: %w",action,res.ExitCode,err)};return nil}
func ensureRuntimeRoot(root string)error{if root!=DefaultRuntimeRoot{return errors.New("Ansible runtime root override rejected")};fi,err:=os.Lstat(root);if errors.Is(err,os.ErrNotExist){if err=os.MkdirAll(root,0700);err!=nil{return err};fi,err=os.Lstat(root)};if err!=nil{return err};if fi.Mode()&os.ModeSymlink!=0||!fi.IsDir()||fi.Mode().Perm()!=0700{return errors.New("unsafe Ansible runtime root")};st,ok:=fi.Sys().(*syscall.Stat_t);if !ok||int(st.Uid)!=os.Geteuid(){return errors.New("Ansible runtime root owner mismatch")};return nil}
func pathsForRequest(req model.ServiceRequest)(map[string]string,error){out:=map[string]string{};for _,purpose:=range []string{"database-data","database-wal","database-logs","database-backup","application-data","application-logs","cache","temporary"}{path,err:=storageplan.PathForPurpose(req,purpose);if err!=nil{return nil,err};if path!=""{out[purpose]=path}};return out,nil}
func serviceUnit(providerID,release string)(string,error){switch providerID{case "postgresql":if release!="16"&&release!="17"{return "",errors.New("unsupported PostgreSQL service release")};return "postgresql-"+release+".service",nil;case "mysql":return "mysqld.service",nil;case "mariadb":return "mariadb.service",nil;case "redis":return "redis.service",nil;case "valkey":return "valkey.service",nil;case "nginx":return "nginx.service",nil;case "apache-httpd":return "httpd.service",nil;case "tomcat":return "tomcat.service",nil;case "nodejs-runtime","python-runtime","podman-runtime":return "",nil;default:return "",fmt.Errorf("Ansible service contract unavailable for provider %q",providerID)}}
func setVRRPPin(v *varsFile){for _,pin:=range v.PlatformPackages{if pin.Purpose=="vrrp"&&pin.Package=="keepalived"{v.VRRPKeepalivedNEVRA=pin.ResolvedVersion;v.VRRPKeepalivedRepository=pin.RepositoryID;return}}}
func requestFromState(op model.Operation,st model.ServiceState)model.ServiceRequest{return model.ServiceRequest{SchemaVersion:1,RequestID:op.ID,ServiceID:st.ID,OperationID:op.ID,IdempotencyKey:op.IdempotencyKey,Category:st.Category,Provider:st.Provider,ReleaseLine:st.ReleaseLine,Topology:st.Topology,Storage:st.Storage,LVM:st.LVM,Network:st.Network,Maintenance:st.Maintenance,Backup:st.Backup,Cluster:st.Cluster,SecretRefs:st.SecretRefs}}
func wipeMany(items [][]byte){for _,item:=range items{wipe(item)}}
func wipe(b []byte){for i:=range b{b[i]=0}}
