package redis

import (
    "bufio"
    "bytes"
    "context"
    "crypto/sha256"
    "encoding/hex"
    "errors"
    "fmt"
    "io"
    "net"
    "os"
    "path/filepath"
    "strconv"
    "strings"
    "time"

    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/backupcrypto"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/executor"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/filesystem"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
    "github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/packageutil"
)

const (
    repoID = "appstream"
    packageName = "redis"
    serviceUnit = "redis.service"
    mainConf = "/etc/redis/redis.conf"
    ownerPath = "/var/lib/layersentryd/state/redis-owner"
    includeMarker = "# LayerSentry managed Redis include"
)

type SecretGetter interface{Get(string)([]byte,error)}
type Provider struct{Runner executor.Runner;DNF packageutil.DNF;Secrets SecretGetter;Backups *backupcrypto.Keyring}
func New(r executor.Runner,s SecretGetter,b *backupcrypto.Keyring)*Provider{return &Provider{Runner:r,DNF:packageutil.DNF{Runner:r},Secrets:s,Backups:b}}
func(p *Provider)ID()string{return "redis"}
func(p *Provider)Category()model.Category{return model.CategoryDatabase}
func(p *Provider)Validate(_ context.Context,r model.ServiceRequest)error{if r.Category!=model.CategoryDatabase{return errors.New("redis category must be database")};if r.Topology!="standalone"{return errors.New("redis cluster/replication is not qualified yet")};if r.ReleaseLine!="6.2"{return errors.New("qualified Rocky AppStream Redis release line is 6.2")};if net.ParseIP(r.Network.ListenAddress)==nil||r.Network.Port==0{return errors.New("redis requires an explicit guest listen IP and TCP port")};if len(r.Network.AllowedCIDRs)==0{return errors.New("redis requires at least one explicit allowed CIDR")};for _,cidr:=range r.Network.AllowedCIDRs{if cidr=="0.0.0.0/0"||cidr=="::/0"{return errors.New("redis refuses an internet-wide allowed CIDR")}};if r.SecretRefs["admin_password"]==""{return errors.New("redis admin_password secret reference is required")};if len(r.Storage)!=0{return errors.New("redis attached-data relocation is not qualified yet; omit storage assignments")};if raw,err:=os.ReadFile(ownerPath);err==nil&&strings.TrimSpace(string(raw))!=r.ServiceID{return errors.New("redis is single-instance on a guest and is already owned by another service")}else if err!=nil&&!errors.Is(err,os.ErrNotExist){return err};return nil}
func(p *Provider)ResolveVersion(ctx context.Context,_ model.ServiceRequest)(string,error){if err:=p.DNF.ValidateRepositories(ctx,repoID);err!=nil{return "",err};v,err:=p.DNF.ResolveLatestFromRepos(ctx,packageName,[]string{repoID});if err!=nil{return "",err};if !versionMatches(v,"6.2"){return "",fmt.Errorf("Rocky AppStream Redis resolved %q outside 6.2",v)};return v,nil}
func(p *Provider)Plan(ctx context.Context,r model.ServiceRequest,resolved string)(model.Plan,error){d,err:=p.DNF.RepositoryDigest(ctx,repoID);if err!=nil{return model.Plan{},err};steps:=[]model.PlanStep{{Name:"repository",Action:"use Rocky AppStream with GPG/TLS verification"},{Name:"packages",Action:"install exact Redis package "+resolved},{Name:"configure",Action:fmt.Sprintf("bind Redis to %s:%d with protected mode, password authentication and a provider-owned persistent RDB directory",r.Network.ListenAddress,r.Network.Port)},{Name:"secret",Action:"resolve admin_password only server-side and install the Redis secret config root:redis 0640 from volatile staging"},{Name:"firewall",Action:"allow only explicit non-public CIDRs before first service start"},{Name:"health",Action:"AUTH and PING over a local RESP connection without exposing the password in argv"}};if r.Backup.Enabled{steps=append(steps,model.PlanStep{Name:"backup-policy",Action:"issue authenticated SAVE locally, copy the RDB through a scoped privileged file action, encrypt with age X25519, then persist only ciphertext"})};sum:=sha256.Sum256([]byte(fmt.Sprintf("%s|%s|%s|%s|%v",r.ServiceID,resolved,repoID,d,steps)));return model.Plan{ID:r.OperationID,ServiceID:r.ServiceID,Provider:p.ID(),ResolvedVersion:resolved,RepositoryID:repoID,RepositoryDigest:d,Digest:hex.EncodeToString(sum[:]),CreatedAt:time.Now().UTC(),Request:r,Steps:steps},nil}
func(p *Provider)Install(ctx context.Context,_ model.Operation,plan model.Plan)error{if raw,err:=os.ReadFile(ownerPath);err==nil&&strings.TrimSpace(string(raw))!=plan.ServiceID{return errors.New("redis is already owned by another service")}else if err!=nil&&!errors.Is(err,os.ErrNotExist){return err};if plan.RepositoryID!=repoID||plan.RepositoryDigest==""{return errors.New("redis plan repository provenance missing")};d,err:=p.DNF.RepositoryDigest(ctx,repoID);if err!=nil{return err};if d!=plan.RepositoryDigest{return errors.New("redis repository configuration drifted after plan confirmation")};return p.DNF.InstallExactFromRepos(ctx,[]string{repoID},plan.ResolvedVersion)}
func(p *Provider)Configure(ctx context.Context,_ model.Operation,plan model.Plan)error{if p.Secrets==nil{return errors.New("secret store unavailable")};if err:=filesystem.AtomicWrite(ownerPath,[]byte(plan.ServiceID+"\n"),0600,"/var/lib/layersentryd/state");err!=nil{return err};secret,err:=p.Secrets.Get(plan.Request.SecretRefs["admin_password"]);if err!=nil{return err};defer zero(secret);if err=validatePassword(secret);err!=nil{return err};dataDir:=p.dataDir(plan.ServiceID);if _,err=p.Runner.Run(ctx,"/usr/bin/install","--directory","--mode=0750","--owner=redis","--group=redis",dataDir);err!=nil{return err};stage,err:=p.stageDir(plan.ServiceID);if err!=nil{return err};stagedConf:=filepath.Join(stage,"redis.conf");defer os.Remove(stagedConf);conf:=fmt.Sprintf("bind %s\nprotected-mode yes\nport %d\ntcp-backlog 511\ntimeout 0\ntcp-keepalive 300\nsupervised systemd\ndaemonize no\ndir %s\ndbfilename dump.rdb\nappendonly no\nrequirepass \"%s\"\n",plan.Request.Network.ListenAddress,plan.Request.Network.Port,dataDir,string(secret));if err=filesystem.AtomicWrite(stagedConf,[]byte(conf),0600,stage);err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0640","--owner=root","--group=redis",stagedConf,p.managedConf(plan.ServiceID));err!=nil{return err};if err=ensureInclude(plan.ServiceID);err!=nil{return err};_,_ = p.Runner.Run(ctx,"/usr/sbin/restorecon","-F",mainConf,p.managedConf(plan.ServiceID));_,_ = p.Runner.Run(ctx,"/usr/sbin/restorecon","-RF",dataDir);return nil}
func(p *Provider)Initialize(context.Context,model.Operation,model.Plan)error{return nil}
func(p *Provider)Join(context.Context,model.Operation,model.Plan)error{return errors.New("redis cluster join is not implemented")}
func(p *Provider)Start(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","enable","--now",serviceUnit);return err}
func(p *Provider)Stop(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","stop",serviceUnit);return err}
func(p *Provider)Restart(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",serviceUnit);return err}
func(p *Provider)Health(ctx context.Context,st model.ServiceState)(model.HealthResult,error){checks:=map[string]string{};r,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","is-active",serviceUnit);if err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:"redis.service is not active"},nil};checks["systemd"]=strings.TrimSpace(r.Stdout);secret,err:=p.Secrets.Get(st.SecretRefs["admin_password"]);if err!=nil{return model.HealthResult{},err};defer zero(secret);reply,err:=redisCommand(ctx,net.JoinHostPort(st.Network.ListenAddress,strconv.Itoa(st.Network.Port)),secret,"PING");if err!=nil||reply!="PONG"{return model.HealthResult{Healthy:false,Checks:checks,Error:"authenticated Redis PING failed"},nil};checks["auth_ping"]="PONG";pkg,err:=p.Runner.Run(ctx,"/usr/bin/rpm","-q",packageName);if err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:"redis package identity unavailable"},nil};version:=strings.TrimSpace(pkg.Stdout);return model.HealthResult{Healthy:true,Version:version,Checks:checks},nil}
func(p *Provider)Upgrade(ctx context.Context,op model.Operation,plan model.Plan)error{if err:=p.Install(ctx,op,plan);err!=nil{return err};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",serviceUnit);return err}
func(p *Provider)Repair(ctx context.Context,_ model.Operation,plan model.Plan)error{if err:=p.Configure(ctx,model.Operation{},plan);err!=nil{return err};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",serviceUnit);return err}
func(p *Provider)Backup(ctx context.Context,op model.Operation,st model.ServiceState)(model.BackupRecord,error){if p.Backups==nil{return model.BackupRecord{},errors.New("backup encryption keyring unavailable")};secret,err:=p.Secrets.Get(st.SecretRefs["admin_password"]);if err!=nil{return model.BackupRecord{},err};defer zero(secret);reply,err:=redisCommand(ctx,net.JoinHostPort(st.Network.ListenAddress,strconv.Itoa(st.Network.Port)),secret,"SAVE");if err!=nil||reply!="OK"{return model.BackupRecord{},errors.New("Redis SAVE failed")};stage,err:=p.backupStage(st.ID);if err!=nil{return model.BackupRecord{},err};plain:=filepath.Join(stage,op.ID+"-redis.rdb");defer os.Remove(plain);if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0600","--owner=layersentry","--group=layersentry",filepath.Join(p.dataDir(st.ID),"dump.rdb"),plain);err!=nil{return model.BackupRecord{},err};plainSHA,plainSize,err:=inspectRDB(plain);if err!=nil{return model.BackupRecord{},err};root:=filepath.Join("/var/lib/layersentryd/backups",st.ID);if err=os.MkdirAll(root,0700);err!=nil{return model.BackupRecord{},err};cipher:=filepath.Join(root,op.ID+"-redis.rdb.age");d,err:=p.Backups.EncryptFile(plain,stage,cipher,root);if err!=nil{return model.BackupRecord{},err};if err=os.Remove(plain);err!=nil{_ = os.Remove(cipher);return model.BackupRecord{},err};return model.BackupRecord{ID:op.ID,ServiceID:st.ID,Provider:p.ID(),Path:cipher,SHA256:d.SHA256,SizeBytes:d.SizeBytes,PlaintextSHA256:plainSHA,PlaintextSizeBytes:plainSize,Encryption:"age-x25519-v1",KeyID:p.Backups.ActiveKeyID(),Verified:true,CreatedAt:time.Now().UTC()},nil}
func(p *Provider)Restore(ctx context.Context,_ model.Operation,st model.ServiceState,b model.BackupRecord)error{if p.Backups==nil{return errors.New("backup encryption keyring unavailable")};if !b.Verified||b.Provider!=p.ID()||b.ServiceID!=st.ID||b.Encryption!="age-x25519-v1"{return errors.New("Redis backup identity/encryption verification failed")};root:=filepath.Join("/var/lib/layersentryd/backups",st.ID);clean:=filepath.Clean(b.Path);rel,err:=filepath.Rel(root,clean);if err!=nil||rel==".."||strings.HasPrefix(rel,".."+string(filepath.Separator)){return errors.New("Redis backup path outside service backup root")};if err=backupcrypto.VerifyCiphertext(clean,root,b.SHA256,b.SizeBytes);err!=nil{return err};stage,err:=p.backupStage(st.ID);if err!=nil{return err};plain:=filepath.Join(stage,b.ID+"-redis-restore.rdb");defer os.Remove(plain);if err=p.Backups.DecryptFile(clean,root,plain,stage);err!=nil{return err};sha,size,err:=inspectRDB(plain);if err!=nil{return err};if sha!=b.PlaintextSHA256||size!=b.PlaintextSizeBytes{return errors.New("decrypted Redis backup integrity mismatch")};if _,err=p.Runner.Run(ctx,"/usr/bin/systemctl","stop",serviceUnit);err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0600","--owner=redis","--group=redis",plain,filepath.Join(p.dataDir(st.ID),"dump.rdb"));err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/sbin/restorecon","-F",filepath.Join(p.dataDir(st.ID),"dump.rdb"));err!=nil{return err};_,err=p.Runner.Run(ctx,"/usr/bin/systemctl","start",serviceUnit);return err}
func(p *Provider)Uninstall(ctx context.Context,_ model.Operation,st model.ServiceState,destroyData bool)error{if destroyData{return errors.New("Redis data destruction requires a separate explicit authorization path")};if _,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","disable","--now",serviceUnit);err!=nil{return err};if err:=removeInclude(st.ID);err!=nil{return err};if err:=os.Remove(p.managedConf(st.ID));err!=nil&&!errors.Is(err,os.ErrNotExist){return err};if err:=os.Remove(ownerPath);err!=nil&&!errors.Is(err,os.ErrNotExist){return err};return p.DNF.Remove(ctx,packageName)}
func(p *Provider)ResidueAudit(ctx context.Context,st model.ServiceState)(map[string]string,error){out:=map[string]string{"customer_data":"preserved"};r,_:=p.Runner.Run(ctx,"/usr/bin/rpm","-q",packageName);if r.ExitCode==0{out["rpm"]="present"}else{out["rpm"]="absent"};r,_=p.Runner.Run(ctx,"/usr/bin/systemctl","is-active",serviceUnit);if r.ExitCode==0{out["service"]="active"}else{out["service"]="inactive"};if _,err:=os.Lstat(p.managedConf(st.ID));err==nil{out["managed_config"]="present"}else{out["managed_config"]="absent"};if _,err:=os.Lstat(ownerPath);err==nil{out["owner"]="present"}else{out["owner"]="absent"};return out,nil}

func(p *Provider)managedConf(id string)string{return filepath.Join("/etc/redis","layersentry-"+id+".conf")}
func(p *Provider)dataDir(id string)string{return filepath.Join("/var/lib/redis","layersentry-"+id)}
func(p *Provider)stageDir(id string)(string,error){path:=filepath.Join("/run/layersentryd/redis-staging",id);if err:=os.MkdirAll(path,0700);err!=nil{return "",err};fi,err:=os.Lstat(path);if err!=nil{return "",err};if !fi.IsDir()||fi.Mode()&os.ModeSymlink!=0||fi.Mode().Perm()&0002!=0{return "",errors.New("unsafe Redis staging directory")};return path,nil}
func(p *Provider)backupStage(id string)(string,error){path:=filepath.Join("/run/layersentryd/backup-staging",id);if err:=os.MkdirAll(path,0700);err!=nil{return "",err};return path,nil}
func ensureInclude(id string)error{raw,err:=os.ReadFile(mainConf);if err!=nil{return err};include:="include /etc/redis/layersentry-"+id+".conf";text:=string(raw);if strings.Contains(text,includeMarker){if !strings.Contains(text,include){return errors.New("Redis LayerSentry include marker does not match service owner")};return nil};if !strings.HasSuffix(text,"\n"){text+="\n"};text+=includeMarker+"\n"+include+"\n";return filesystem.AtomicWrite(mainConf,[]byte(text),0644,"/etc/redis")}
func removeInclude(id string)error{raw,err:=os.ReadFile(mainConf);if err!=nil{return err};include:="include /etc/redis/layersentry-"+id+".conf";lines:=strings.Split(string(raw),"\n");out:=make([]string,0,len(lines));removedMarker,removedInclude:=false,false;for _,line:=range lines{if strings.TrimSpace(line)==includeMarker{removedMarker=true;continue};if strings.TrimSpace(line)==include{removedInclude=true;continue};out=append(out,line)};if !removedMarker||!removedInclude{return errors.New("Redis LayerSentry include state is missing; refusing blind cleanup")};return filesystem.AtomicWrite(mainConf,[]byte(strings.Join(out,"\n")),0644,"/etc/redis")}
func validatePassword(b []byte)error{if len(b)<16||len(b)>128{return errors.New("Redis admin password must be 16..128 printable ASCII characters")};for _,c:=range b{if c<33||c>126||c=='"'||c=='\\'{return errors.New("Redis admin password must be printable ASCII excluding quote/backslash")}};return nil}
func redisCommand(ctx context.Context,address string,password []byte,command string)(string,error){d:=net.Dialer{Timeout:3*time.Second};conn,err:=d.DialContext(ctx,"tcp",address);if err!=nil{return "",err};defer conn.Close();_ = conn.SetDeadline(time.Now().Add(5*time.Second));if err=writeRESP(conn,[]byte("AUTH"),password);err!=nil{return "",err};r:=bufio.NewReader(io.LimitReader(conn,64<<10));reply,err:=readSimple(r);if err!=nil||reply!="OK"{return "",errors.New("Redis AUTH rejected")};if err=writeRESP(conn,[]byte(command));err!=nil{return "",err};return readSimple(r)}
func writeRESP(w io.Writer,args ...[]byte)error{if _,err:=fmt.Fprintf(w,"*%d\r\n",len(args));err!=nil{return err};for _,a:=range args{if _,err:=fmt.Fprintf(w,"$%d\r\n",len(a));err!=nil{return err};if _,err:=w.Write(a);err!=nil{return err};if _,err:=io.WriteString(w,"\r\n");err!=nil{return err}};return nil}
func readSimple(r *bufio.Reader)(string,error){line,err:=r.ReadString('\n');if err!=nil{return "",err};if len(line)<3||!strings.HasSuffix(line,"\r\n"){return "",errors.New("invalid Redis reply")};payload:=strings.TrimSuffix(line[1:],"\r\n");switch line[0]{case '+':return payload,nil;case '-':return "",errors.New("Redis command failed");default:return "",errors.New("unexpected Redis reply type")}}
func inspectRDB(path string)(string,int64,error){fi,err:=os.Lstat(path);if err!=nil{return "",0,err};if fi.Mode()&os.ModeSymlink!=0||!fi.Mode().IsRegular()||fi.Size()<16{return "",0,errors.New("Redis RDB backup is empty or unsafe")};f,err:=os.Open(path);if err!=nil{return "",0,err};defer f.Close();head:=make([]byte,9);if _,err=io.ReadFull(f,head);err!=nil{return "",0,err};if !bytes.HasPrefix(head,[]byte("REDIS")){return "",0,errors.New("Redis RDB header verification failed")};if _,err=f.Seek(0,0);err!=nil{return "",0,err};h:=sha256.New();if _,err=io.Copy(h,f);err!=nil{return "",0,err};return hex.EncodeToString(h.Sum(nil)),fi.Size(),nil}
func versionMatches(nevra,prefix string)bool{rest:=strings.TrimPrefix(nevra,packageName+"-");if rest==nevra{return false};if i:=strings.IndexByte(rest,':');i>=0{rest=rest[i+1:]};return rest==prefix||strings.HasPrefix(rest,prefix+".")}
func zero(b []byte){for i:=range b{b[i]=0}}
