package keyvalue

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/backupcrypto"
	"github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/executor"
	"github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/filesystem"
	"github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/model"
	"github.com/adaptgurus/cloudstack/tools/layersentry/single-os/agent/internal/packageutil"
)

const repoID = "appstream"

type SecretGetter interface{ Get(string) ([]byte,error) }
type Spec struct{ ID,Package,ServiceUnit,ReleasePrefix,MainConf,ConfigDir,DataRoot,OSUser string }
type Provider struct{ Runner executor.Runner; DNF packageutil.DNF; Secrets SecretGetter; Backups *backupcrypto.Keyring; Spec Spec }

func Redis(r executor.Runner,s SecretGetter,b *backupcrypto.Keyring)*Provider{return New(r,s,b,Spec{ID:"redis",Package:"redis",ServiceUnit:"redis.service",ReleasePrefix:"6.2",MainConf:"/etc/redis/redis.conf",ConfigDir:"/etc/redis",DataRoot:"/var/lib/redis",OSUser:"redis"})}
func Valkey(r executor.Runner,s SecretGetter,b *backupcrypto.Keyring)*Provider{return New(r,s,b,Spec{ID:"valkey",Package:"valkey",ServiceUnit:"valkey.service",ReleasePrefix:"8.0",MainConf:"/etc/valkey/valkey.conf",ConfigDir:"/etc/valkey",DataRoot:"/var/lib/valkey",OSUser:"valkey"})}
func New(r executor.Runner,s SecretGetter,b *backupcrypto.Keyring,spec Spec)*Provider{return &Provider{Runner:r,DNF:packageutil.DNF{Runner:r},Secrets:s,Backups:b,Spec:spec}}
func(p *Provider)ID()string{return p.Spec.ID}
func(p *Provider)Category()model.Category{return model.CategoryDatabase}
func(p *Provider)Validate(_ context.Context,r model.ServiceRequest)error{if r.Category!=model.CategoryDatabase{return fmt.Errorf("%s category must be database",p.Spec.ID)};if r.Topology!="standalone"{return fmt.Errorf("%s cluster/replication is not qualified yet",p.Spec.ID)};if r.ReleaseLine!=p.Spec.ReleasePrefix{return fmt.Errorf("qualified %s release line is %s",p.Spec.ID,p.Spec.ReleasePrefix)};if net.ParseIP(r.Network.ListenAddress)==nil||r.Network.Port==0{return fmt.Errorf("%s requires an explicit guest listen IP and TCP port",p.Spec.ID)};if len(r.Network.AllowedCIDRs)==0{return fmt.Errorf("%s requires at least one explicit allowed CIDR",p.Spec.ID)};for _,cidr:=range r.Network.AllowedCIDRs{if cidr=="0.0.0.0/0"||cidr=="::/0"{return fmt.Errorf("%s refuses an internet-wide allowed CIDR",p.Spec.ID)}};if r.SecretRefs["admin_password"]==""{return fmt.Errorf("%s admin_password secret reference is required",p.Spec.ID)};if len(r.Storage)!=0{return fmt.Errorf("%s attached-data relocation is not qualified yet; omit storage assignments",p.Spec.ID)};raw,err:=os.ReadFile(p.ownerPath());if err==nil&&strings.TrimSpace(string(raw))!=r.ServiceID{return fmt.Errorf("%s is single-instance on a guest and is already owned by another service",p.Spec.ID)};if err!=nil&&!errors.Is(err,os.ErrNotExist){return err};return nil}
func(p *Provider)ResolveVersion(ctx context.Context,_ model.ServiceRequest)(string,error){if err:=p.DNF.ValidateRepositories(ctx,repoID);err!=nil{return "",err};v,err:=p.DNF.ResolveLatestFromRepos(ctx,p.Spec.Package,[]string{repoID});if err!=nil{return "",err};if !versionMatches(p.Spec.Package,v,p.Spec.ReleasePrefix){return "",fmt.Errorf("Rocky AppStream %s resolved %q outside %s",p.Spec.ID,v,p.Spec.ReleasePrefix)};return v,nil}
func(p *Provider)Plan(ctx context.Context,r model.ServiceRequest,resolved string)(model.Plan,error){d,err:=p.DNF.RepositoryDigest(ctx,repoID);if err!=nil{return model.Plan{},err};steps:=[]model.PlanStep{{Name:"repository",Action:"use Rocky AppStream with GPG/TLS verification"},{Name:"packages",Action:"install exact "+p.Spec.ID+" package "+resolved},{Name:"secret",Action:"resolve admin_password server-side and persist only its SHA-256 ACL verifier, never plaintext"},{Name:"configure",Action:fmt.Sprintf("bind %s to %s:%d with protected mode and provider-owned RDB directory",p.Spec.ID,r.Network.ListenAddress,r.Network.Port)},{Name:"firewall",Action:"allow only explicit non-public CIDRs before first service start"},{Name:"health",Action:"AUTH and PING over a local RESP connection without password argv exposure"}};if r.Backup.Enabled{steps=append(steps,model.PlanStep{Name:"backup-policy",Action:"issue authenticated SAVE locally, stage RDB through a scoped privileged copy, encrypt with age X25519, and persist only ciphertext"})};sum:=sha256.Sum256([]byte(fmt.Sprintf("%s|%s|%s|%s|%s|%v",r.ServiceID,p.Spec.ID,resolved,repoID,d,steps)));return model.Plan{ID:r.OperationID,ServiceID:r.ServiceID,Provider:p.ID(),ResolvedVersion:resolved,RepositoryID:repoID,RepositoryDigest:d,Digest:hex.EncodeToString(sum[:]),CreatedAt:time.Now().UTC(),Request:r,Steps:steps},nil}
func(p *Provider)Install(ctx context.Context,_ model.Operation,plan model.Plan)error{if raw,err:=os.ReadFile(p.ownerPath());err==nil&&strings.TrimSpace(string(raw))!=plan.ServiceID{return fmt.Errorf("%s is already owned by another service",p.Spec.ID)}else if err!=nil&&!errors.Is(err,os.ErrNotExist){return err};if plan.RepositoryID!=repoID||plan.RepositoryDigest==""{return fmt.Errorf("%s plan repository provenance missing",p.Spec.ID)};d,err:=p.DNF.RepositoryDigest(ctx,repoID);if err!=nil{return err};if d!=plan.RepositoryDigest{return fmt.Errorf("%s repository configuration drifted after plan confirmation",p.Spec.ID)};return p.DNF.InstallExactFromRepos(ctx,[]string{repoID},plan.ResolvedVersion)}
func(p *Provider)Configure(ctx context.Context,_ model.Operation,plan model.Plan)error{if p.Secrets==nil{return errors.New("secret store unavailable")};if err:=filesystem.AtomicWrite(p.ownerPath(),[]byte(plan.ServiceID+"\n"),0600,"/var/lib/layersentryd/state");err!=nil{return err};secret,err:=p.Secrets.Get(plan.Request.SecretRefs["admin_password"]);if err!=nil{return err};defer zero(secret);if len(secret)<12||len(secret)>1024{return errors.New("key-value administrator password length outside 12..1024 bytes")};verifier:=sha256.Sum256(secret);dataDir:=p.dataDir(plan.ServiceID);if _,err=p.Runner.Run(ctx,"/usr/bin/install","--directory","--mode=0750","--owner="+p.Spec.OSUser,"--group="+p.Spec.OSUser,dataDir);err!=nil{return err};stage,err:=p.stageDir(plan.ServiceID);if err!=nil{return err};stagedConf:=filepath.Join(stage,p.Spec.ID+".conf");defer os.Remove(stagedConf);conf:=fmt.Sprintf("bind %s\nprotected-mode yes\nport %d\ntcp-backlog 511\ntimeout 0\ntcp-keepalive 300\nsupervised systemd\ndaemonize no\ndir %s\ndbfilename dump.rdb\nappendonly no\nuser default on resetpass #%s ~* &* +@all\n",plan.Request.Network.ListenAddress,plan.Request.Network.Port,dataDir,hex.EncodeToString(verifier[:]));if err=filesystem.AtomicWrite(stagedConf,[]byte(conf),0600,stage);err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0640","--owner=root","--group="+p.Spec.OSUser,stagedConf,p.managedConf(plan.ServiceID));err!=nil{return err};if err=p.ensureInclude(plan.ServiceID);err!=nil{return err};_,_ = p.Runner.Run(ctx,"/usr/sbin/restorecon","-F",p.Spec.MainConf,p.managedConf(plan.ServiceID));_,_ = p.Runner.Run(ctx,"/usr/sbin/restorecon","-RF",dataDir);return nil}
func(p *Provider)Initialize(context.Context,model.Operation,model.Plan)error{return nil}
func(p *Provider)Join(context.Context,model.Operation,model.Plan)error{return fmt.Errorf("%s cluster join is not implemented",p.Spec.ID)}
func(p *Provider)Start(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","enable","--now",p.Spec.ServiceUnit);return err}
func(p *Provider)Stop(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","stop",p.Spec.ServiceUnit);return err}
func(p *Provider)Restart(ctx context.Context,_ model.Operation,_ model.ServiceState)error{_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",p.Spec.ServiceUnit);return err}
func(p *Provider)Health(ctx context.Context,st model.ServiceState)(model.HealthResult,error){checks:=map[string]string{};r,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","is-active",p.Spec.ServiceUnit);if err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:p.Spec.ServiceUnit+" is not active"},nil};checks["systemd"]=strings.TrimSpace(r.Stdout);secret,err:=p.Secrets.Get(st.SecretRefs["admin_password"]);if err!=nil{return model.HealthResult{},err};defer zero(secret);reply,err:=respCommand(ctx,net.JoinHostPort(st.Network.ListenAddress,strconv.Itoa(st.Network.Port)),secret,"PING");if err!=nil||reply!="PONG"{return model.HealthResult{Healthy:false,Checks:checks,Error:"authenticated "+p.Spec.ID+" PING failed"},nil};checks["auth_ping"]="PONG";pkg,err:=p.Runner.Run(ctx,"/usr/bin/rpm","-q",p.Spec.Package);if err!=nil{return model.HealthResult{Healthy:false,Checks:checks,Error:p.Spec.ID+" package identity unavailable"},nil};version:=strings.TrimSpace(pkg.Stdout);return model.HealthResult{Healthy:true,Version:version,Checks:checks},nil}
func(p *Provider)Upgrade(ctx context.Context,op model.Operation,plan model.Plan)error{if err:=p.Install(ctx,op,plan);err!=nil{return err};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",p.Spec.ServiceUnit);return err}
func(p *Provider)Repair(ctx context.Context,_ model.Operation,plan model.Plan)error{if err:=p.Configure(ctx,model.Operation{},plan);err!=nil{return err};_,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","restart",p.Spec.ServiceUnit);return err}
func(p *Provider)Backup(ctx context.Context,op model.Operation,st model.ServiceState)(model.BackupRecord,error){if p.Backups==nil{return model.BackupRecord{},errors.New("backup encryption keyring unavailable")};secret,err:=p.Secrets.Get(st.SecretRefs["admin_password"]);if err!=nil{return model.BackupRecord{},err};defer zero(secret);reply,err:=respCommand(ctx,net.JoinHostPort(st.Network.ListenAddress,strconv.Itoa(st.Network.Port)),secret,"SAVE");if err!=nil||reply!="OK"{return model.BackupRecord{},fmt.Errorf("%s SAVE failed",p.Spec.ID)};stage,err:=p.backupStage(st.ID);if err!=nil{return model.BackupRecord{},err};plain:=filepath.Join(stage,op.ID+"-"+p.Spec.ID+".rdb");defer os.Remove(plain);if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0600","--owner=layersentry","--group=layersentry",filepath.Join(p.dataDir(st.ID),"dump.rdb"),plain);err!=nil{return model.BackupRecord{},err};plainSHA,plainSize,err:=inspectRDB(plain);if err!=nil{return model.BackupRecord{},err};root:=filepath.Join("/var/lib/layersentryd/backups",st.ID);if err=os.MkdirAll(root,0700);err!=nil{return model.BackupRecord{},err};cipher:=filepath.Join(root,op.ID+"-"+p.Spec.ID+".rdb.age");d,err:=p.Backups.EncryptFile(plain,stage,cipher,root);if err!=nil{return model.BackupRecord{},err};if err=os.Remove(plain);err!=nil{_ = os.Remove(cipher);return model.BackupRecord{},err};return model.BackupRecord{ID:op.ID,ServiceID:st.ID,Provider:p.ID(),Path:cipher,SHA256:d.SHA256,SizeBytes:d.SizeBytes,PlaintextSHA256:plainSHA,PlaintextSizeBytes:plainSize,Encryption:"age-x25519-v1",KeyID:p.Backups.ActiveKeyID(),Verified:true,CreatedAt:time.Now().UTC()},nil}
func(p *Provider)Restore(ctx context.Context,_ model.Operation,st model.ServiceState,b model.BackupRecord)error{if p.Backups==nil{return errors.New("backup encryption keyring unavailable")};if !b.Verified||b.Provider!=p.ID()||b.ServiceID!=st.ID||b.Encryption!="age-x25519-v1"{return fmt.Errorf("%s backup identity/encryption verification failed",p.Spec.ID)};root:=filepath.Join("/var/lib/layersentryd/backups",st.ID);clean:=filepath.Clean(b.Path);rel,err:=filepath.Rel(root,clean);if err!=nil||rel==".."||strings.HasPrefix(rel,".."+string(filepath.Separator)){return errors.New("backup path outside service backup root")};if err=backupcrypto.VerifyCiphertext(clean,root,b.SHA256,b.SizeBytes);err!=nil{return err};stage,err:=p.backupStage(st.ID);if err!=nil{return err};plain:=filepath.Join(stage,b.ID+"-"+p.Spec.ID+"-restore.rdb");defer os.Remove(plain);if err=p.Backups.DecryptFile(clean,root,plain,stage);err!=nil{return err};sha,size,err:=inspectRDB(plain);if err!=nil{return err};if sha!=b.PlaintextSHA256||size!=b.PlaintextSizeBytes{return errors.New("decrypted key-value backup integrity mismatch")};if _,err=p.Runner.Run(ctx,"/usr/bin/systemctl","stop",p.Spec.ServiceUnit);err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/bin/install","--mode=0600","--owner="+p.Spec.OSUser,"--group="+p.Spec.OSUser,plain,filepath.Join(p.dataDir(st.ID),"dump.rdb"));err!=nil{return err};if _,err=p.Runner.Run(ctx,"/usr/sbin/restorecon","-F",filepath.Join(p.dataDir(st.ID),"dump.rdb"));err!=nil{return err};_,err=p.Runner.Run(ctx,"/usr/bin/systemctl","start",p.Spec.ServiceUnit);return err}
func(p *Provider)Uninstall(ctx context.Context,_ model.Operation,st model.ServiceState,destroyData bool)error{if destroyData{return fmt.Errorf("%s data destruction requires a separate explicit authorization path",p.Spec.ID)};if _,err:=p.Runner.Run(ctx,"/usr/bin/systemctl","disable","--now",p.Spec.ServiceUnit);err!=nil{return err};if err:=p.removeInclude(st.ID);err!=nil{return err};if err:=os.Remove(p.managedConf(st.ID));err!=nil&&!errors.Is(err,os.ErrNotExist){return err};if err:=os.Remove(p.ownerPath());err!=nil&&!errors.Is(err,os.ErrNotExist){return err};return p.DNF.Remove(ctx,p.Spec.Package)}
func(p *Provider)ResidueAudit(ctx context.Context,st model.ServiceState)(map[string]string,error){out:=map[string]string{"customer_data":"preserved"};r,_:=p.Runner.Run(ctx,"/usr/bin/rpm","-q",p.Spec.Package);if r.ExitCode==0{out["rpm"]="present"}else{out["rpm"]="absent"};r,_=p.Runner.Run(ctx,"/usr/bin/systemctl","is-active",p.Spec.ServiceUnit);if r.ExitCode==0{out["service"]="active"}else{out["service"]="inactive"};if _,err:=os.Lstat(p.managedConf(st.ID));err==nil{out["managed_config"]="present"}else{out["managed_config"]="absent"};if _,err:=os.Lstat(p.ownerPath());err==nil{out["owner"]="present"}else{out["owner"]="absent"};return out,nil}

func(p *Provider)ownerPath()string{return filepath.Join("/var/lib/layersentryd/state",p.Spec.ID+"-owner")}
func(p *Provider)managedConf(id string)string{return filepath.Join(p.Spec.ConfigDir,"layersentry-"+id+".conf")}
func(p *Provider)dataDir(id string)string{return filepath.Join(p.Spec.DataRoot,"layersentry-"+id)}
func(p *Provider)stageDir(id string)(string,error){path:=filepath.Join("/run/layersentryd",p.Spec.ID+"-staging",id);if err:=os.MkdirAll(path,0700);err!=nil{return "",err};return safeDir(path)}
func(p *Provider)backupStage(id string)(string,error){path:=filepath.Join("/run/layersentryd/backup-staging",id);if err:=os.MkdirAll(path,0700);err!=nil{return "",err};return safeDir(path)}
func safeDir(path string)(string,error){fi,err:=os.Lstat(path);if err!=nil{return "",err};if !fi.IsDir()||fi.Mode()&os.ModeSymlink!=0||fi.Mode().Perm()&0002!=0{return "",errors.New("unsafe key-value staging directory")};return path,nil}
func(p *Provider)ensureInclude(id string)error{raw,err:=os.ReadFile(p.Spec.MainConf);if err!=nil{return err};marker:="# LayerSentry managed "+p.Spec.ID+" include";include:="include "+p.managedConf(id);text:=string(raw);if strings.Contains(text,marker){if !strings.Contains(text,include){return errors.New("LayerSentry include marker does not match service owner")};return nil};if !strings.HasSuffix(text,"\n"){text+="\n"};text+=marker+"\n"+include+"\n";return filesystem.AtomicWrite(p.Spec.MainConf,[]byte(text),0644,p.Spec.ConfigDir)}
func(p *Provider)removeInclude(id string)error{raw,err:=os.ReadFile(p.Spec.MainConf);if err!=nil{return err};marker:="# LayerSentry managed "+p.Spec.ID+" include";include:="include "+p.managedConf(id);lines:=strings.Split(string(raw),"\n");out:=make([]string,0,len(lines));for _,line:=range lines{trim:=strings.TrimSpace(line);if trim==marker||trim==include{continue};out=append(out,line)};return filesystem.AtomicWrite(p.Spec.MainConf,[]byte(strings.Join(out,"\n")),0644,p.Spec.ConfigDir)}
func versionMatches(pkg,nevra,prefix string)bool{rest:=strings.TrimPrefix(nevra,pkg+"-");if rest==nevra{return false};if i:=strings.IndexByte(rest,':');i>=0{rest=rest[i+1:]};return rest==prefix||strings.HasPrefix(rest,prefix+".")}
func inspectRDB(path string)(string,int64,error){fi,err:=os.Lstat(path);if err!=nil{return "",0,err};if fi.Mode()&os.ModeSymlink!=0||!fi.Mode().IsRegular()||fi.Size()<9{return "",0,errors.New("RDB backup is empty or unsafe")};f,err:=os.Open(path);if err!=nil{return "",0,err};defer f.Close();head:=make([]byte,5);if _,err=io.ReadFull(f,head);err!=nil{return "",0,err};if !bytes.Equal(head,[]byte("REDIS")){return "",0,errors.New("RDB header verification failed")};if _,err=f.Seek(0,0);err!=nil{return "",0,err};h:=sha256.New();if _,err=io.Copy(h,f);err!=nil{return "",0,err};return hex.EncodeToString(h.Sum(nil)),fi.Size(),nil}
func respCommand(ctx context.Context,address string,password []byte,command string)(string,error){d:=net.Dialer{Timeout:3*time.Second};conn,err:=d.DialContext(ctx,"tcp",address);if err!=nil{return "",err};defer conn.Close();_ = conn.SetDeadline(time.Now().Add(5*time.Second));rw:=bufio.NewReadWriter(bufio.NewReader(conn),bufio.NewWriter(conn));if err=writeRESP(rw,[][]byte{[]byte("AUTH"),password});err!=nil{return "",err};if err=rw.Flush();err!=nil{return "",err};reply,err:=readRESP(rw.Reader);if err!=nil||reply!="OK"{if err==nil{err=errors.New("authentication rejected")};return "",err};if err=writeRESP(rw,[][]byte{[]byte(command)});err!=nil{return "",err};if err=rw.Flush();err!=nil{return "",err};return readRESP(rw.Reader)}
func writeRESP(w io.Writer,args [][]byte)error{if _,err:=fmt.Fprintf(w,"*%d\r\n",len(args));err!=nil{return err};for _,a:=range args{if _,err:=fmt.Fprintf(w,"$%d\r\n",len(a));err!=nil{return err};if _,err:=w.Write(a);err!=nil{return err};if _,err:=io.WriteString(w,"\r\n");err!=nil{return err}};return nil}
func readRESP(r *bufio.Reader)(string,error){line,err:=r.ReadString('\n');if err!=nil{return "",err};if len(line)<3||!strings.HasSuffix(line,"\r\n"){return "",errors.New("invalid RESP reply")};body:=strings.TrimSuffix(line[1:],"\r\n");switch line[0]{case '+':return body,nil;case '-':return "",errors.New("server rejected command")};return "",errors.New("unexpected RESP reply type")}
func zero(b []byte){for i:=range b{b[i]=0}}
